### ISSUE TITLE
Sintaxis funcionalosa + return 

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#107]
CREO que si se define un método como
```Wollok
method m() = return "Hola"
```
Rompe.

Esto puede que esté correcto, en ese caso habría que agregarlo a los sanities.

**Comment by PalumboN** [comment]
Algo similar pasa dentro de un if:
```wollok
	method tieneUnEdificio(){
		if (not self.estaOcupado()){
			return false
		}
		else (return self.ocupante().esEdificio())
	}
```

**Comment by nscarcella** [comment]
@PalumboN `method m() = return "Hola"` es sintácticamente incorrecto. `return` no es una expresión. Tampoco sería valido poner una asignación o la declaración de una variable.

En el caso del `if` es distinto porque el cuerpo de un `if` o `try` no necesita ser una expresión.

No podemos agregar código que no parsea a los sanities, en general se entiende que si algo es sintácticamente incorrecto fallaría el parseo antes que la ejecución (en los tests del parser está cubierto).

**Comment by PalumboN** [comment]
@nscarcella genial! 

Creo que este issue lo cargué principalmente por el problema del `if`, que es el que recuerdo haberlo visto en un juego.

El `return` no me acuerdo cómo era en Xtext pero me parece bien que **no** sea una expresión.

**Comment by nscarcella** [comment]
@PalumboN No estoy seguro si terminé de entender cuál es el problema que decías en el if.

Poner un `return` entre paréntesis no es valido, porque el paréntesis solamente sirve para agrupar expresiones. Podés poner llaves o poner sólo el `return` y podés poner paréntesis alrededor del valor retornado, pero así como está no está bien.
