### ISSUE TITLE
Problemas con los punto y coma

### ISSUE THREAD

**Issue by AngeliMatias** [uqbar-project/wollok-ts#108]
En [este juego](https://github.com/pdepjm/2021-o-tpi-juego-hellfish) hay un `;` en arma.wlk que rompe el validator.

**Comment by fdodino** [comment]
El problema es en el parser, por algún motivo se permiten los puntos y coma en una sentence pero no en la definición de variables:

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/dfbb3135-fe32-45be-857c-531e3aad3233)

Si me preguntás a mí, que de error siempre 😆 , pero bueno... es inconsistente soportarlo en los métodos y no en las definiciones.
