### ISSUE TITLE
Bloques dentro de bloques confunde self

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#109]
Este test:
```Wollok
object o {
	var property block = null

	method prueba() { 
		{
			self.block({ self.magia() }) 
		}.apply()
	}

	method magia() { 
		console.println("PIOLA")
	}
}

test "Se confunde self" {
	o.prueba()
	o.block().apply()
}
```

Tira este error diciendo que **el bloque grande no entiende `magia()`**
```bash
     wollok.lang.MessageNotUnderstoodException: {
			self.block({ self.magia() }) 
		} does not undersand magia()
			self.block({ self.magia() }) 
		} does not undersand magia()
	at wollok.lang.Object.messageNotUnderstood(messageName, parameters) [wollok/lang.wlk:206:3]
	at wollok.lang.Closure#c31fb331-ab7c-4fd7-a82f-3e5cfd4beb6e.<apply>() [src/tests.wtest:14:15]
	at wollok.lang.Closure.apply(parameters) [wollok/lang.wlk:2757:3]
	at src.tests."Se confunde self" [src/tests.wtest:23:1]
	at root [--:--]
     Derived from TypeScript stack
```

**Comment by asanzo** [comment]
@FerRomMu @julimr se fijan si esto sigue pasando en ts???

**Comment by FerRomMu** [comment]
El error persiste.

**Comment by asanzo** [comment]
Estoy lejos de una compu, pero mirándolo mejor me pregunto: ¿Cuál es la semántica que espero al escribir "self" en un bloque?  ¿Siempre es el objeto raíz? En este caso lo que parece estar pasando es que el self.magia() está suponiendo que ese self es el que existe en el contexto inmediatamente superior ( el bloque "grande" de los dos bloques que existen en ese ejemplo) pero en realidad debería tomar el self del object o.

 ¿Y qué onda en XTexT? ¿Cómo anda esto ahí?

Y me pregunto qué pasa en este caso:

```wollok
object a {
    method foo(){
         const b = object {
               method bar() = self.elSaludo()
               method elSaludo() = "hola, soy b"
         }
         b.bar()
    }
    method elSaludo() = "hola, soy a"
}
```

Si yo hago `a.foo()` ¿qué pasa en ts y en xtext? ¿Ese self es a o es b? Yo esperaría que sea b....

Pero creo que este issue es especialmente para los bloques, y que no tiene mucho que ver con otras definiciones.

**Comment by asanzo** [comment]
Entiendo por lo que veo [acá](https://github.com/uqbar-project/wollok-ts/blob/a71193f68a604eb638682a32f794c2ba14e661e1/src/model.ts#L867) que en wollok-ts los bloques son Singletons anónimos (como un `object {}`) y ya. Entonces lo que yo decía arriba sí es relevante, porque su contexto se maneja igual que un singleton, y no debería.

@nscarcella ¿Puede ser que esto se resuelva [acá](https://github.com/uqbar-project/wollok-ts/blob/a71193f68a604eb638682a32f794c2ba14e661e1/src/interpreter/runtimeModel.ts#L168) evitando setear self en el caso de que el RuntimeObject en cuestión sea un closure?

No sé cómo averiguar si es un closure, igual.

**Comment by nscarcella** [comment]
@asanzo 
> @nscarcella ¿Puede ser que esto se resuelva [acá](https://github.com/uqbar-project/wollok-ts/blob/a71193f68a604eb638682a32f794c2ba14e661e1/src/interpreter/runtimeModel.ts#L168) evitando setear self en el caso de que el RuntimeObject en cuestión sea un closure?

Nono, porque un closure ES un objeto y necesita saber que self es sí mismo. Lo que querés que funcione distinto en los closures es el método `apply`, que tiene que evaluarse en un contexto que sobreescriba self (eso pasa en [la native de `apply`](https://github.com/uqbar-project/wollok-ts/blob/a71193f68a604eb638682a32f794c2ba14e661e1/src/wre/lang.ts#L698) ) imagino que la forma en que encontramos el self correcto ahora mismo no es suficientemente astuta...

Sin haberlo pensado mucho, el código parece asumir que un bloque siempre está en un contexto en el que se hereda la referencia a `self` correcta pero en este caso en que el bloque se define dentro de otro bloque no es así. Lo que habría que hacer es masticar esa linea de código un poquito más, cosa de seguir buscando hasta llegar al objeto correcto.

Nada, es un bug en TS. Bien encontrado. No creo que sea un cambio particularmente difícil, pero si hay que tener cuidado de no romper otra cosa todavía más rara. Cuando tenga un minuto lo miro yo.
