### ISSUE TITLE
toString de un Object

### ISSUE THREAD

**Issue by ezequielPereyra** [uqbar-project/wollok-ts#114]
```wollok
object pepita {}
```

Si en _xtext_ hacemos `pepita.toString()` nos devuelve "pepita" (el nombre del objeto).

Pero si lo hacemos en _wollok-ts_, nos devuelve el FQN.

Habría que ver con qué versión nos queremos quedar y agregar los sanity tests correspondientes a _wollok-language_.

**Comment by asanzo** [comment]
Pasa lo mismo con las clases:

![image](https://user-images.githubusercontent.com/5421992/172214530-ed3aba43-48af-41ee-a066-502d7dc78fef.png)

**Comment by asanzo** [comment]
Sobre cómo debería ser, eso lo charlamos mucho al hacer el REPL original. Cómo se ven en consola los objetos en una materia inicial de programación es uuultra importante. Por una cuestión de que no quiero agregar aún más cambios al lenguaje, y que además tengo un poco de miedo de las consecuencias pedagógicas, yo haría que los toString() de objetos nombrados, objetos anónimos e instancias de clase sean iguales a los de Wollok XText.
Y en ppio en inglés, después vemos de agregar internationalization como tiene Wollok XText.

**Comment by asanzo** [comment]
Esto lo estamos discutiendo acá, discusión de donde va a salir algo más cerradito y coherente con suerte:
https://github.com/uqbar-project/wollok-language/issues/140
