### ISSUE TITLE
Validación: no debería pedir override para el initialize de los test, clases y objetos

### ISSUE THREAD

**Issue by julimr** [uqbar-project/wollok-ts#123]
Error en consola: 
`[WARNING]: shouldUseOverrideKeyword at src/temporada1.wtest:15`

[Link al repo](https://github.com/pdepjm/2021-o-drCasaEnClase)

**Comment by nscarcella** [comment]
Esto se había discutido pero no creo que hayamos llegado a una conclusión. A mí la verdad me importa poco, pero tal vez habría que chequear con el resto...

**Comment by fdodino** [comment]
+1 a que no lo pida, al menos en los describes queda feo

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/e7b2a921-6ce0-4402-a143-1b94686a096d)
