### ISSUE TITLE
Error de parseo está rompiendo la función validate()

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#128]
Ejemplo:

```wollok
c l as s A { }
```

El tema es que la función `buildEnvironment` tira un error en lugar de levantar los problemas en forma individual:

```ts
function buildEnvironment(files: List<{ name: string, content: string }>, baseEnvironment: Environment = fromJSON<Environment>(WRE)): Environment {

  return link(files.map(({ name, content }) => {
    try {
      return parse.File(name).tryParse(content)
    } catch (error) {
      throw new Error(`Failed to parse ${name}: ${(error as Error).message}`)
    }
  }), baseEnvironment)
}
```

**Comment by PalumboN** [comment]
Y qué comportamiento esperamos para ese código del demonio?

Que no se rompa el parser, ok al menos. Pero qué te muestro? Claramente eso no es código :P

**Comment by nscarcella** [comment]
Nono, claro. Eso lo mostras para que lo veamos *nosotros* y podamos
arreglar lo que pasa. Un alumno nunca debería verlo.

**Comment by PalumboN** [comment]
Ahí lo problé, y después de los cambios de @ivojawer en el parser esto tiene este comportamiento:

<img width="571" alt="image" src="https://github.com/uqbar-project/wollok-ts/assets/4098184/045883f5-1629-4725-bc90-d7327fc28527">

Y el parser no se rompe y si arreglás el código se recupera ;)

Para mí ya está cerrado.

**Comment by fdodino** [comment]
jajaja, estaba probando exactamente lo mismo. Para mí este comportamiento está perfecto, no se si se arregló con un try/catch del lado de wollok-lsp-ide, pero +1 a cerrarlo.
