### ISSUE TITLE
Agregar un match otherwise para evitar el try catch

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#149]
Hace falta este `try - catch`? Es porque el `match` cuando no encuentra ninguno explota o por otra cosa que puede pasar?

Tal vez estaría bueno tener algo onda 
```wollok
match(node)(
   when(Environment)(env => ...),
   ...,
   otherwise(node => ...)
)
```

_Originally posted by @PalumboN in https://github.com/uqbar-project/wollok-lsp-ide/pull/60#discussion_r1141394513_

**Comment by PalumboN** [comment]
Lo intenté y hay una cosa molesta de imports entre archivos. El workaround es usar `when(Node)`.

**Comment by fdodino** [comment]
@PalumboN te parece que cerremos este issue? Yo creo que el `when(Node)` es suficiente...

**Comment by PalumboN** [comment]
@fdodino ahí tiré un PR con lo que tenía implementado por ahí: https://github.com/uqbar-project/wollok-ts/pull/238
