### ISSUE TITLE
Fix ** precedence

### ISSUE THREAD

**Issue by nscarcella** [uqbar-project/wollok-ts#15]
Currently the parser has a TODO in the operators where the ** is duplicated. Removing the first instance of ** causes the parsing of WRE to fail (Probably an ambiguity with the comment syntax or the * having more precedence than the **, making the sencond * an issue).

Adding a lookAhead might fix the problem but it would be nice to make it generic so we don't need to handle that case separately from the current implementation. Maybe something in the lines of checking after an operator that the next character is not another operator?

**Comment by nscarcella** [comment]
I believe this was already fixed by @JuanFdS

**Comment by JuanFdS** [comment]
Oh, it should have been fixed in this PR: https://github.com/uqbar-project/wollok-ts/pull/31/files

I forgot to close the issue :see_no_evil:
