### ISSUE TITLE
New validation: const without initialization

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#151]
Este program es válido?

```wollok
program p {
    const b
}
```

Creía que había una validación para que las constantes siempre se inicializaran.

**Comment by juanbono** [comment]
Estuve buscando un poco y la validation `shouldInitializeGlobalReference` se encarga de checkear eso, pero solo para constantes top-level. Voy a ver si puedo adaptarla para que funcione dentro de un program.
