### ISSUE TITLE
Re-pensar la API

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#156]
Fijarse cómo se usa la VM en otros proyectos y ofrecer una mejor API.

### CLI
- En este PR se movió lógica https://github.com/uqbar-project/wollok-ts-cli/pull/72

### LSP
- Este archivo https://github.com/uqbar-project/wollok-lsp-ide/blob/master/server/src/utils/wollok.ts

### Mobile
- Este archivo https://github.com/uqbar-project/wollok-mobile/blob/dev/src/utils/wollok-helpers.ts

**Comment by fdodino** [comment]
@PalumboN , creo que faltaría encarar solamente la parte Mobile. La parte de LSP que quedaba la empecé a mover en otro PR que va a salir, por ahí lo puedo renombrar usando este ticket.

**Comment by fdodino** [comment]
Respecto a [la implementación de los helpers de Mobile](https://github.com/uqbar-project/wollok-mobile/blob/dev/src/utils/wollok-helpers.ts):

- allFields: ya existe en model
- allMethods: ya existe en model
- allVariables: hay que crearla

```ts
export function allVariables(node: Method | Test): List<Variable> {
	return node.sentences().filter(is('Variable'))
}
```

- isNamedSingleton: hay que agregarlo y de paso usarlo en Evaluation.globalSingletons:

```ts
const globalSingletons = environment.descendants.filter((node: Node): node is Singleton => node.is(Singleton) && !!node.name)
```

- methodLabel: el de Method devuelve el fully qualified name + la aridad. Yo propongo usar un fullLabel

```ts
export function methodLabel(method: Method): string {
	return `${method.name}(${method.parameters.map(_ => _.name).join(',')})`
}
```

- literalClassFQN: 

```ts
export function literalClassFQN(literal: Literal): Name {
	return `wollok.lang.${upperCaseFirst(typeof literal.value)}`
}
```

para mí se reemplaza por `literalValueToClass` en `helpers`

- containerOf y allScopedVariables, son métodos que habría que ver cómo los migramos porque hay un CodeContainer
- methodFQN: es el label que está implementado en la clase Method (Model) pero sin llamar a super
- methodByFQN: habría que migrarlo a helpers
- entityMemberLabel: lo dejaría, no tengo contexto para ver por qué chequean si es método y por qué no se puede usar un label común
- entityMemberFQN: lo mismo que el anterior, a mí me gustaría ver por qué fue necesario armar algo custom
- isError: curioso que no hay ningún método, lo migraría a extensions (BaseProblem y Problem son interfaces, qué macana)
- TestResult, TestRun, FinishedExecutionState, interpretTest: son helpers para ejecutar el test, dado que no se llama a wollok-ts-cli yo lo dejaría como está.
- isNullExpression: en helpers hay dos lugares donde necesitaríamos tener esa abstracción, hay que migrarla
- executionFor: es un interesante método, hay que migrarlo (no se bien dónde)
- projectToJSON: lo migraría
- isComplete: se puede migrar también
- isEmptyArgument: lo migraría

**Comment by fdodino** [comment]
Cierro el issue, voy a abrir otro para migrar las 4 funciones que quedan.
