### ISSUE TITLE
Fully qualified name cuando un closure o un anonymous object está en el REPL

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#168]
Me está viniendo como fully qualified name

`wollok.lang.Closure#undefined` cuando en el REPL hago

```wollok
const criterio = { 5 + 1 }
```

Lo mismo si hago

```wollok
const robustiano = object { var j = 1 }
```

Recibo como fully qualified name `wollok.lang.Object#undefined`

No estoy muy seguro de si tiene que ver con que estoy en el contexto del REPL.

**Comment by PalumboN** [comment]
Esto era por lo mismo que https://github.com/uqbar-project/wollok-ts/issues/165 o na' que ver?

**Comment by fdodino** [comment]
Entiendo que es otra cosa, es propio de wollok-ts :

```ts
    @cached
    get fullyQualifiedName(): Name {
      const parent = getPotentiallyUninitializedLazy(this, 'parent')
      const label = this.is(Singleton)
        ? this.name ?? `${this.superclass!.fullyQualifiedName}#${this.id}`
        : this.name!.replace(/\.#/g, '')

      return parent?.is(Package) || parent?.is(Describe)
        ? `${parent.fullyQualifiedName}.${label}`
        : label
    }
```

línea 269 ... de model.ts. Para mí si metés un 

```ts
        // ? this.name ?? `${this.superclass!.fullyQualifiedName}#${this.id}`
        ? this.name ?? `${this.superclass!.fullyQualifiedName}${this.id ? '#' + this.id ?? ''}`
```

o algo similar me sirve. Pero como es wollok-ts quiero charlarlo con alguien más antes de mandarme.

**Comment by PalumboN** [comment]
Raro que esos objetos no tengan `id`, hay que investigar un toque más qué pasa

**Comment by fdodino** [comment]
Cierro el issue porque con los últimos cambios del diagrama dinámico estamos mostrando `Anonymous`

```ts
      const label = this.is(Singleton)
        ? this.name ?? `${this.superclass!.fullyQualifiedName}#${this.id ?? 'anonymous'}`
```
