### ISSUE TITLE
Warning variable sin usar solo debería reportarse sobre la variable

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-ts#170]
<img width="236" alt="image" src="https://github.com/uqbar-project/wollok-ts/assets/18614957/a3e7cd96-63f7-4966-8441-17d1450d842d">

La validation `shouldNotDefineUnusedVariables` solo debería marcarse hasta `var color`

**Comment by fdodino** [comment]
qué loco, yo siempre naturalicé que era solo el nombre de la variable, como en Xtext:

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/bdc95e89-44a5-4f84-a1c0-1ef6e3002069)

Pero bueno, hay que ver qué tan fácil es toquetearlo...

**Comment by PalumboN** [comment]
Yyy entiendo que habría que jugar con el `sourceMap` del Problem. 

La pregunta es si hacerlo en TS o en el LSP 🤔

**Comment by fdodino** [comment]
Yo pensaba que lo debería hacer el TS, porque vos podés reportar cada error con un SourceMap o algo así. Hace bocha que no lo toco pero con NicoS nos habíamos puesto de acuerdo como para poder configurarlo desde TS...
