### ISSUE TITLE
Se permite instanciar una clase con un método abstracto

### ISSUE THREAD

**Issue by Juancete** [uqbar-project/wollok-ts#180]
Con este código de ejemplo

```wollok
class Ave {

  method volar() = 5 + self.extra()

  method extra()
}
```

Permite en la consola y en los tests hacer `const pepita = new Ave()`. Al enviar el mensaje extra() a pepita obtengo el siguiente error:

> ✗ Evaluation Error!
  wollok.lang.MessageNotUnderstoodException: an Ave does not understand extra()

**Comment by fdodino** [comment]
En RuntimeModel, este método 

```ts
  protected *execNew(node: New): Execution<RuntimeValue> {
    const args: Record<Name, RuntimeObject> = {}
    for(const arg of node.args) args[arg.name] = yield* this.exec(arg.value)

    yield node

    const target = node.instantiated.target ?? raise(new Error(`Could not resolve reference to instantiated module ${node.instantiated.name}`))

    // acá debería chequearse
    if (target.isAbstract) raise(new Error(`${node.instantiated.name} is an abstract class, you cannot generate instances`))
    //

    return yield* this.instantiate(target, args)
  }
```

Faltaría agregar tests y relacionado a eso falta un if más por si `!target.is(Class)` (por https://github.com/uqbar-project/wollok-ts-cli/issues/35 y https://github.com/uqbar-project/wollok-ts-cli/issues/36, no deberíamos hacer new de objects, ni de mixines, ni de otra cosa que no sean clases)

**Comment by Juancete** [comment]
@fdodino y @PalumboN 

Ya hay un branch [aquí](https://github.com/uqbar-project/wollok-ts/tree/fix-%23180-%2335-%2336-should-not-get-an-instance) con el fix. 

Estoy intentando hacer el test, pero no encuentro realmente donde ponerlo. Estuve investigando model.test.ts pero creo que no corresponde porque si bien se puede analizar el AST, tengo que obtener una instancia para validar que no se pueda instanciar. Entiendo que tampoco está en el linker o el validator. 

Se me ocurre que va en los test de language. Tengo estos test que agregué momentáneamente a mano para probar.
```wollok
/**
  * Scenario: an abstract class
  */
class MyClass {
  method a()
}

/**
  * Tests
  */
describe "classes - an abstract class" {

  test "cound not be instantiated" {
    assert.throwsException { new MyClass() }
  }

}
```

```wollok
/**
  * Scenario: a WKO
  */
object pepita {
  var energy = 0
  method energyLevel(){
    return energy
  }
  
  method addEnergy(amount){
    energy = energy + amount
  }
}

describe "an object" {
  test "cound not be instantiated" {
    assert.throwsException { new pepita() }
  }
}
```

y agrego en misias.wtest
```wollok
  test "a mixin could not be instantiated" {
    assert.throwsException { new Energy() }
  }
```

Si está correcto, entiendo que habría que meter primeros los cambios en Lang para luego poder correr los tests postas para aprobar este PR, es correcto ? o por ahí me estoy perdiendo de como testear en este proyecto.

**Comment by fdodino** [comment]
Hola @Juancete ,
        sí, revisando el `model.test` no se hace ninguna evaluación en runtime del modelo, lo que se testea es estático, así que +1 a que 

1. el test esté en wollok-language
2. para eso, hay que crear un PR de wollok-language, y lo metemos en la bolsa de cosas que están pendientes (las de @juanbono )
3. liberamos una versión nueva de wollok-language
4. armás el PR de ésto para wollok-ts
5. liberamos también los PRs que están dando vueltas (@juanbono again)
6. y liberamos un release nuevo 4.0.6 de wollok-ts

@PalumboN @nscarcella @ivojawer , qué les parece?

**Comment by PalumboN** [comment]
+💯 a todo! Agrego 2 cositas:

1. También habría que meter la validación sobre el código (validator), no? O eso ya anda? Para eso hay tests parecido a los Xtext, también en lang
2. Yo dejaría que los mixines (no abstractos) se puedan instanciar. Esta es una decisión estratégica que se tomó en su momento, para impulsar la fusión de Mixines y Clases en una sola cosa en un futuro lejano :)

El resto to'piola! Tiren los PRs a los repos, probando que pasen los tests localmente, y después mergeamos / releaseamos / updateamos / seguimos releaseando / seguimos updateando....(*)


(*) Una cosa sobre esto @fdodino, necesitamos revisar todo el proceso de Release. A mí me gustaría que las ramas de development se apunten entre ellas en los distintos repos, así no se traban los PR. Después al momento de releasear nos aseguramos que todos tengan la versión correcta. Pa' charlar.

**Comment by fdodino** [comment]
> +💯 a todo! Agrego 2 cositas:
> 
> 1. También habría que meter la validación sobre el código (validator), no? O eso ya anda? Para eso hay tests parecido a los Xtext, también en lang

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/064933b8-a8df-4ffd-b335-e96ea2b20e6f)

sí, ya está implementado y hay sanity tests del validador

> 2. Yo dejaría que los mixines (no abstractos) se puedan instanciar. Esta es una decisión estratégica que se tomó en su momento, para impulsar la fusión de Mixines y Clases en una sola cosa en un futuro lejano :)

ok, mixines yo lo doy en Algoritmos 2 de UNSAM, a mí me sirve que se puedan instanciar

> 
> El resto to'piola! Tiren los PRs a los repos, probando que pasen los tests localmente, y después mergeamos / releaseamos / updateamos / seguimos releaseando / seguimos updateando....(*)
> 
> (*) Una cosa sobre esto @fdodino, necesitamos revisar todo el proceso de Release. A mí me gustaría que las ramas de development se apunten entre ellas en los distintos repos, así no se traban los PR. Después al momento de releasear nos aseguramos que todos tengan la versión correcta. Pa' charlar.

Dale, si querés esta semana hablamos para ver cómo implementar eso...

**Comment by Juancete** [comment]
@PalumboN, hablando hoy con @fdodino vamos en un primer PR que las clases abstractas no se puedan instancias y luego modificamos los mixines para que se puedan instanciar dado que es un cambio más profundo

**Comment by PalumboN** [comment]
Ahhh piola! Pensé que ya estaba funcionando así.
Sisi habrimos un issue para lo otro :)
