### ISSUE TITLE
El parser no debería ignorar los comentarios

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#183]
Hoy el parser descarta todos los comentarios para armar el AST. Eso trae muchos inconvenientes

- para el highlighter
- para el autocomplete, no podemos mostrar la documentación de módulos (clases, objetos, mixines) ni de mensajes
- para generar la página guía completa de lenguaje como [hoy tiene Xtext](https://www.wollok.org/documentacion/wollokdoc/)

La propuesta incluye anotaciones para poder después incorporarlo como parte de la estructura de un AST.

**Comment by fdodino** [comment]
@ivojawer , ésto no lo considerás ya en el PR del Formatter?

**Comment by ivojawer** [comment]
Sip, #189 implementa una primera version muy basica, me habia olvidado que existia este issue 😅
