### ISSUE TITLE
Reporta como variable sin utilizar una referencia que está dentro de un bloque

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#193]
```wollok
object reportes {

	const property tours = []

        // <- ACA
	const currentYear = new Date().year()
        //
	
	method addTour(tour) {
		tours.add(tour)
	}

	method toursPendientesDeConfirmacion() = tours.count{ tour => !tour.confirmado() }

	method totalToursDelAnio() = tours.filter{ tour => tour.fechaSalida().year() == currentYear }.sum{ tour => tour.montoTotal() }

}
```

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/2cf6d182-40fe-4b69-b299-f0c9bccc3c7f)

**Comment by PalumboN** [comment]
También había uno que decía lo mismo para referencias dentro de listas / sets (se podría generalizar a cualquier literal que pueda tener código dentro).

No lo encontré, no recuerdo si se resolvió, solo lo digo para chusmear :P
