### ISSUE TITLE
Validación falla con Malformed sentence sobre comentarios

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok-ts#207]
Hay un error que salta si un método sólo tiene internamente un comentario, el error dice:

`La siguiente regla falló: Malformed sentence`

![image](https://github.com/uqbar-project/wollok-ts/assets/715971/33e4977b-d4d3-4233-aa3b-55e00c6b6af5)

Un método sin sentencias ni comentarios se toma como válido, pero si tiene sólo un comentario, se marca el comentario como un error sintáctico.

La versión de wollok que estoy usando es
```
$ wollok --version
0.2.0
```

**Comment by PalumboN** [comment]
Related to https://github.com/uqbar-project/wollok-ts/issues/202

**Comment by mmatos** [comment]
Otro ejemplo fuera del contexto de un método:

![image](https://github.com/uqbar-project/wollok-ts/assets/715971/e920d9b2-9ddc-48c2-8647-a4d322d210c8)

Si quito el comentario de línea anterior deja de chillar

![image](https://github.com/uqbar-project/wollok-ts/assets/715971/5d6bb9d5-8693-4102-8e86-5847cbd57b6b)

Si lo muevo para abajo, es el segundo comentario el que se marca
![image](https://github.com/uqbar-project/wollok-ts/assets/715971/6245e44c-bd7d-482e-a281-8bb1a3080bf8)

**Comment by PalumboN** [comment]
Related https://github.com/uqbar-project/wollok-ts/issues/202

**Comment by PalumboN** [comment]
Los comentarios al final del archivo ya no fallan

<img width="296" alt="image" src="https://github.com/uqbar-project/wollok-ts/assets/4098184/855b9357-e4e0-4715-ae3e-25aea4806d4a">


Todavía falta arreglar dentro de un método
