### ISSUE TITLE
El REPL permite instanciar objetos sin parametrizar atributos sin un valor por default

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok-ts#209]
No debería ser posible instanciar una clase sin pasar un valor para atributos sin defaults:
![image](https://github.com/uqbar-project/wollok-ts-cli/assets/715971/25ce085b-c9ee-4767-ba90-c0124e37f8c8)

Esa misma instanciación se marca como un error en la validación del programa, pero el REPL no lo limita y en el diagrama se muestra que está apuntando a null

**Comment by fdodino** [comment]
@mmatos , ahí lo estoy viendo. De paso me hiciste encontrar un error en el validador, que no tomaba en cuenta las asignaciones dentro del método initialize. Bien ahí!

Lo que hice fue dejar el mismo comportamiento que Xtext, que es:
- si vos adrede ponés `var lugar = null`, no se queja ni el validador ni el intérprete (deja pasarlo en runtime y te queda apuntando a null)
- si vos no inicializás la variable, no podés instanciar y te dice cuáles son las variables sin inicializar
