### ISSUE TITLE
Validación con Mixines cuando no se usan (shouldImplementAllMethodsInHierarchy)

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#211]
Con este repo del concurso: https://github.com/pdepmartestm/2023-tpgame-dulce-de-leche-tentacion

<img width="896" alt="image" src="https://github.com/uqbar-project/wollok-ts/assets/4098184/32846f72-c05a-441e-a067-528160fbdfa6">

Es una jerarquía grande que va asignando atributos a medida que hereda (no me acordaba de ese feature, quizá eso lo rompa).
No hay mixines en el proyecto.

**Comment by fdodino** [comment]
Bueno, @PalumboN, ahí estuve viendo el issue:

- el proyecto tiene packages duplicados: en el archivo constants.wlk define un `package ENEMIES {` que colisiona con la carpeta Enemies y adentro los archivos. Con lo cual todo se rompe mal y es imposible que el validador conteste algo razonable.

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/bdc2b442-06ee-47b5-a54f-d7b7f755b351)

- más allá de eso, me armé un proyecto aparte y logré replicarlo. Primero funciona correctamente con la jerarquía Enemy > GameVisual:
 
![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/fa638014-ab35-4e9a-9a14-fb052cd1ca91)

Y después cuando puse el método remove como abstracto, saltó la validación:

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/3e0f0b1f-97ca-42b8-a4e7-b2d30bcdb3cb)

## Qué se puede mejorar

1. Cambiemos por supuesto el mensaje que no corresponde con el error (asume que la jerarquía es de mixines y se puede dar este caso de llamar a un método abstracto)
2. Por otra parte, acá en ts deberíamos marcar únicamente la clase, mostrar todo es muy verboso y queda medio raro. Y de paso le pasamos cuáles son los métodos que tienen ese problema para darle contexto al usuario.

**Comment by fdodino** [comment]
Algo así @ivojawer @PalumboN 

![image](https://github.com/uqbar-project/wollok-ts/assets/4549002/1ce57bb3-0f49-49bc-be5e-8ac7f6321f80)

**Comment by PalumboN** [comment]
Buenísimo.

Pero el problema es el `override` o el `super`? Entiendo que debería ser el override.

Por eso yo propongo que la validación esté en el método, y no en la clase. Ahí se podría sobreescribir cada `override` incorrecto por separado.
