### ISSUE TITLE
Nombre de archivo separados con puntos falla con shouldNotDuplicatePackageName

### ISSUE THREAD

**Issue by Juancete** [uqbar-project/wollok-ts#236]
Por ejemplo se crea un archivo **example.otro.wlk** rompe cualquier definición que tengamos dentro del archivo, sea class, object, etc.

Ejemplo: 
```wlk
class Ave {

}
```

Marcando en class el siguiente error: 

> Package duplicado(shouldNotDuplicatePackageName)

**Comment by PalumboN** [comment]
Sí, eso fue predicho por el gran Dodain en este comentario: https://github.com/uqbar-project/wollok-ts/issues/166#issuecomment-1756299642.
Básicamente colisiona con los fqn.

Yo por ahora optaría por lo sano de no dejar poner más de un punto al nombre del archivo, lo agregué al comentario de ese mismo issue donde está mi plan ~~malvado~~ de 3 pasos.

**Comment by Juancete** [comment]
Gracias @PalumboN  por el aviso. No lo había encontrado y creé uno nuevo. 

Awante los planes malvados 🍸
