### ISSUE TITLE
Si defino un const en un archivo y en el REPL escribo const el comportamiento es raro

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#271]
Ejemplo: tengo un archivo `example.wlk` con esta definición

```wollok
const aves = []
```

Luego en el REPL hago

```wollok
const aves = [1, 2]
```

- En el diagrama dinámico se ve el const que está en el REPL, con las referencias a 1 y 2
- Pero si evalúo aves.size() me da 0

![image](https://github.com/user-attachments/assets/4c609734-ba10-4feb-aa28-db50bd0e1f1a)

**Comment by fdodino** [comment]
@PalumboN @ivojawer confirmo que se solucionó! 

![image](https://github.com/user-attachments/assets/7ccc4728-19c7-416e-bbfc-0eedfb86c86d)

Cierro el issue también.

**Comment by PalumboN** [comment]
Pero llegas a acceder al aves que tiene a pepita también?

**Comment by fdodino** [comment]
> Pero llegas a acceder al aves que tiene a pepita también?

sí, sí, @PalumboN , cuando arranco

![image](https://github.com/user-attachments/assets/c3f1a9e0-48af-4af6-8710-b807dba97398)

Cuando hago const aves ... se actualiza la referencia

![image](https://github.com/user-attachments/assets/adb4190b-e9a4-411e-a63a-bb8c9b868a99)
