### ISSUE TITLE
En lun List no permite remover números flotantes

### ISSUE THREAD

**Issue by epernia** [uqbar-project/wollok-ts#276]
Si se ejecuta, por ejemplo:

[2.5].remove(2.5)

Ejecuta bien, pero retorna la misma lista [2.5] en lugar de una lista vacía []

Probando con Wollok TS veo que con enteros, booleandos o strings remueve bien, solo no puede remover números flotantes. 

Probé en el viejo Wollok Xtext y si se permite remover flotantes correctamente.

**Comment by PalumboN** [comment]
Que loco este bug! Gracias @epernia por reportar.
