### ISSUE TITLE
Se puede redefinir el ===

### ISSUE THREAD

**Issue by Juancete** [uqbar-project/wollok-ts#298]
Permite al usuario redefinir la identidad.

Por ejemplo 
```wlk
class ClaseLoca {
  method bla() = 3

  override method === (otroObjeto ) = false 
}
```

y en el repl hacemos 
```wlk
const pumba = new ClaseLoca()

pumba === pumba 
> false
```

**Comment by PalumboN** [comment]
Cuál sería el error esperado? Un warning / error en el IDE? Y en la consola?

Hay más métodos de este estilo? (Pienso en alguno de la familia `toString()`)

**Comment by fdodino** [comment]
Yo creo que de los métodos es el único que me parece que estaría bueno no redefinir. El toString() está bien, el `==` también...

Y esperaría que tire error el Validator, como chiche podríamos hacer lo que hace Smalltalk, y hardcodear el `===` para que siempre use la identidad y no tome en cuenta un método redefinido.

**Comment by fdodino** [comment]
Cosas para hacer:
- revisar el archivo index.ts del Validador, concretamente acá

```ts
when(Method)(() => ({ onlyLastParameterCanBeVarArg, nameShouldNotBeKeyword, methodShouldHaveDifferentSignature, shouldNotOnlyCallToSuper, shouldUseOverrideKeyword, possiblyReturningBlock, shouldNotUseOverride, shouldMatchSuperclassReturnValue, shouldNotDefineNativeMethodsOnUnnamedSingleton, overridingMethodShouldHaveABody, getterMethodShouldReturnAValue, shouldHaveBody })),
```

hay que llamar a una nueva función

- la función tiene que tirar error si el name es `===` y no estamos en Object, además de tener 1 argumento, hay una función que devuelve un booleano para ver si falla, se tipa como `<Error>` si queremos que tire error, y hay una función para pasar parámetros (no nos importa) y otra función para marcar el sourceMap (es decir la parte del archivo que hay que resaltar). En este caso el sourceMap tiene que ser del nombre del método (ya hay una función que hace eso, `sourceMapForNodeName`).

Te paso un ejemplo simple para que veas cómo es un validador:

```ts
export const nameShouldNotBeKeyword = error<Parameter | Variable | Field | Method>(node =>
  !RESERVED_WORDS.includes(node.name || ''),
valuesForNodeName,
sourceMapForNodeName,
)
```

en este caso la función que valida que no uses palabras reservadas devuelve un booleano, después le pasa como parámetro al mensaje de error todas las palabras reservadas (es dinámico) y por último devuelve el source map para que marque el nombre. 

El nombre de tu función tiene que ser algo como `shouldNotRedefineIdentity`, vamos a ver después para qué te sirve.

- hay que agregar en wollok-language un test para validarlo. Para eso vos al hacer git clone vas a hacer `npm run buildWRE` y en la carpeta `language` vas a tener el repo de wollok-language. Hay que crear una branch y generar un test de validador, en la carpeta `test/validations/`. El nombre del archivo debería ser algo como `shouldNotRedefineIdentity`, que es el nombre de la función que definiste en ts.

Fijate cómo está implementado el `test/validations/nameShouldNotBeKeyword.wpgm`:

```wollok
@Expect(code="nameShouldNotBeKeyword", level="error", expectedOn="object")
object object {
  method invalidParam(@Expect(code="nameShouldNotBeKeyword", level="error", expectedOn="test") test) = true
}

class SomeClass {
  @Expect(code="nameShouldNotBeKeyword", level="error", expectedOn="var")
  var var = 11

  @Expect(code="nameShouldNotBeKeyword", level="error", expectedOn="var")
  method var() = var
  
  @Expect(code="nameShouldNotBeKeyword", level="error", expectedOn="method")
  method method() {
    @Expect(code="nameShouldNotBeKeyword", level="error", expectedOn="const")
    const const = 1
  }

}

@Expect(code="nameShouldNotBeKeyword", level="error", expectedOn="program")
program program {
  console.println(new SomeClass())
}
```

Acá se prueba de todo, en nuestro caso podrías testear un `object` (Singleton, wko) y un `class`, además de un `describe` para chequear que al definir un método no puedas usar `===`. Lo tenés que hacer en un archivo `.wtest` porque no podés escribir un `describe` dentro de un archivo que no sea `.wtest`.

Fijate que en `expectedOn` vos vas a poner el string `===` para chequear que coincida dónde se subraya el error.

- Por último el mensaje de error hay que internacionalizarlo, eso se hace acá:

`src/resources/validationMessages/en.json` y `es.json` respectivamente, en el repo de Wollok Language, y va asociado al código de error (el nombre de la función) su correspondiente mensaje.

@MVitelli
