### ISSUE TITLE
Add i18n capabilities for validator messages

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#43]
We should think a way to reuse [Wollok Xtext `.properties` file](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties). To do so:

- we could port properties file to wollok-language
- then use a second lambda function to pass an array of possible strings (default, empty array)
- and use an internationalized `.ini` file

We could use [this package](https://www.npmjs.com/package/ini)

**Comment by nscarcella** [comment]
@fdodino can we start by choosing a file format for the messages and moving those to language? Lets find out how we can do that from Xtext and we can adapt the TS side in base of that.

**Comment by fdodino** [comment]
Ok, hablemos a ver cómo te parece seguir...

**Comment by fdodino** [comment]
Esto ya está encarado en wollok-lsp-ide. Lo cierro.
