### ISSUE TITLE
Replace tslint.json with eslint

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#44]
Since TSLint will be deprecated in 2020, it is necessary to migrate from `tslint.json` to **typescript-eslint** rules. Please see

- A [migration tool](https://github.com/typescript-eslint/tslint-to-eslint-config)
- The [original issue](https://github.com/palantir/tslint/issues/4534)

**Comment by fdodino** [comment]
This could be a bit tricky if you are in a multimodule repo, but you can see it in Wollok Linter repo (https://github.com/uqbar-project/wollok-linter)

**Comment by rodr0m4** [comment]
I started working on this :)

There are a couple of places where I don't know if we want to be more strict with the linting, or we should add an 'off' (mostly from usages of the `!.` operator, which does not have a rule in tslint :P )

I'll reference this issue in my PR

**Comment by nscarcella** [comment]
This is already done in `next` branch.
