### ISSUE TITLE
Reference to describe?

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#46]
Now the linker make a reference with a describe node (with the same name) as target. Could this scenario be possible?

Example test:
```ts
    it('should target describe??', () => {
      const environment = link([
        Package('p', {
          imports: [
            Import(Reference('r.G')),
          ],
        })(
          Describe('G')(
            Fixture()(
              Reference('G'),
            )
          )
        ),
        Package('r')(
          Class('G')(),
        ),
      ] as PackageNode<Filled>[], WRE)

      const describe = environment.getNodeByFQN<DescribeNode>('p.G')
      const clazz = environment.getNodeByFQN<ClassNode>('r.G')
      const reference = describe.fixtures()[0].body.sentences[0] as ReferenceNode<Linked>

      reference.should.target(describe)
    })
```

**Comment by nscarcella** [comment]
@PalumboN I don't think this should be possible, because describes (I believe) should not be referenceable. They should not contribute themselves to the scope, son in your example the reference should point to the imported class.

If you think this is not the expected behavior lets start a thread in wollok-dev.

**Comment by PalumboN** [comment]
@nscarcella Estoy de acuerdo con que no deberían ser referenciables, pero creo que eso no es lo que estaba pasando, de ahí [este cambio](https://github.com/uqbar-project/wollok-language/pull/50) que tuvimos que meter en language.

Habría que ver si ese test pasa con la versión actual / si hay uno análogo con el assert correcto.

**Comment by nscarcella** [comment]
Bueno, efectivamente había un problema, pero venía del parser.

El tema es que ese test que pedís no debería poder construirse, o mejor dicho, no representa Wollok válido, porque tanto los Describes como los Tests siempre tienen que tener sus nombres entre `"`s, mientras que las clases nunca pueden tener esos nombres. Es imposible tener un Describe que se llame como una Class... O, al menos, **ahora** que arreglé el parser es imposible.

Ya agregué tests para verificar estas cosas, así que cuando mergiemos next ya no debería ser un problema.
