### ISSUE TITLE
Should add unraw as a dependency in the readme?

### ISSUE THREAD

**Issue by guillep** [uqbar-project/wollok-ts#54]
Branch: next

I tried to run the tests using

```bash
$ npm test
```

And I got a compile time error because `unraw` was not available. I got after it doing `npm install unraw` but it is not clear this is the way to go...

**Comment by nscarcella** [comment]
Yep. We must have fucked up the package dependencies in a revert or something. Good catch!

**Comment by nscarcella** [comment]
@guillep On a closer look, the dependency to unraw is in `package.json`. Is it possible you switched to the `next` branch and forget to run `npm install` after?

**Comment by guillep** [comment]
Very possible. That's why I added an issue and not a PR, I was not sure and it was late yesterday.

In any case, I don't know what the policy is. Should the readme list dependencies? Or being in the package.json is enough?
I'm ok with closing the issue too, I'm not emotionally attached to it :)

**Comment by nscarcella** [comment]
That´s OK. Dependencies are not usually listed on the readme unless their are relevant somehow to the user.

Closing the issue now. Thanks!
