### ISSUE TITLE
Actualizar con los cambios de las keys y el client

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#61]
- Descomentar los tests de las keys luego de https://github.com/uqbar-project/wollok-language/pull/68. Ver de además agregar un test para el 'ANY'
- Hacer el native de `doCellSize` para usarlo desde https://github.com/uqbar-project/wollok-run-client/pull/12

**Comment by tfloxolodeiro** [comment]
Si descomentamos los tests de ts, se necesitaría la ultima versión en master de lang para correrlos. El problema que tuve con esto es que master de lang también incluye tests de audio que todavía no están implementados en ts y que por eso explotan. Tal vez se puede hacer un tag especial de lang?
