### ISSUE TITLE
No funciona (MNU) el native de addVisualCharacterIn

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#62]
Falta implementarlo en el mirror.

Dijimos de deprecar este método. Creo que podríamos implementarlo en el mirror tirando una excepción de que está deprecado en esta versión.

**Comment by PalumboN** [comment]
Después de cargar el issue recordé que esta primitiva no fue implementada porque es la más controversial. Estamos pensando en deprecarla, junto con otras (buscar issue al respecto)... Habría que analizar si lo hacemos por una eventual retrocompatibilidad o podemos evitarnos el dolor de cabeza.

**Comment by lspigariol** [comment]
evitémosnos el dolor de cabeza
es mas fácil modificar los ejemplos que haya por alli, en caso de haber
alguno

**Comment by PalumboN** [comment]
Related https://github.com/uqbar-project/wollok-ts/issues/71

**Comment by PalumboN** [comment]
Resolved in https://github.com/uqbar-project/wollok-ts/pull/90
