### ISSUE TITLE
Checkout wollok-language using ssh instead of https

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#92]
We are using `https` method for Wollok Language checkout in `fetchLanguage` script. We should migrate to ssh ASAP.

**Comment by fdodino** [comment]
Uhm... supongo @nscarcella que el commit 88b55a0 se refiere al issue 92 de wollok-language.

Por otra parte, hice este cambio

```ts
const WOLLOK_LANGUAGE_REPO = 'git@github.com:uqbar-project/wollok-language.git'
```

en mi entorno local y borré la carpeta `language`. Me la descargó lo más bien. Esto obviamente depende de que tengas configurado ssh localmente, me parece por ahí lo más acertado, no se cómo simular su ausencia de credenciales para mostrar un mensaje de error que ayude a la persona a entender que tiene que descargarlo vía ssh y ya no usar más https.

**Comment by nscarcella** [comment]
@fdodino 
> Uhm... supongo @nscarcella que el commit [88b55a0](https://github.com/uqbar-project/wollok-ts/commit/88b55a0229d648ca67eeb44212efe9cedcac59f1) se refiere al issue 92 de wollok-language.

No tengo idea qué pasó. Lo más cercano que recuerdo es referenciar el issue 72, pero este no... Ni idea....

> 
> Por otra parte, hice este cambio
> 
> ```ts
> const WOLLOK_LANGUAGE_REPO = 'git@github.com:uqbar-project/wollok-language.git'
> ```

Joya, mañana lo pruebo
