### ISSUE TITLE
Colisiones entre nombre de objeto, program e import

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#96]
En este juego: https://github.com/Franpanozzo/saveStallin-game

Hay un import, un program y un objeto que se llaman iguales:
https://github.com/Franpanozzo/saveStallin-game/blob/e60f1abc934e18b0e162fe4dbfd4226177baf053/src/game.wpgm#L1-L5

Y se trula y no sabe con quien hablar.

**Comment by nscarcella** [comment]
@PalumboN en qué quedó está discusión? Se puede cerrar esto ya?

**Comment by asanzo** [comment]
Mi opinión es que en https://github.com/uqbar-project/wollok-language/issues/122 hay que tener una discusión y de allí saldrá una definición. Podemos cerrar esto, y enfocar ahí la discusión
