### ISSUE TITLE
Referencias a excepciones en try-catch

### ISSUE THREAD

**Issue by ezequielPereyra** [uqbar-project/wollok-ts#98]
Si hacemos algo como: 

``` wollok
try {
	...
}
catch e: wollok.lang.DomainException {
	...
}
```

Falla el parseo con el siguiente error:

```
-- PARSING FAILED --------------------------------------------------

  4 |           throw new DomainException()
  5 |   }
> 6 |   catch e: wollok.lang.DomainException {}
    |                 ^
  7 |
  8 |   assert.that(true)

Expected one of the following:

'@', '{', comment, sentence, whitespace
```

Dejo [este repo](https://github.com/ezequielPereyra/wollok_prueba_try_catch) con una prueba chiquita para este caso.

**Comment by nscarcella** [comment]
Sí, sospecho que en algún momento se esperaba que importes la excepción y FQN no tenía que funcionar, pero veo que en xtext funciona bien, así que no veo problema de soportarlo. El fix de @juanbono parece ser el correcto, así que todo va bien.

@ezequielPereyra sería un golazo agregar un sanity que cubra esto. No hace falta nada muy loco, con tener algún catch con un FQN en el tipo alcanza y sobra. Podrías crear un PR a language para agregar tu test ahí?

**Comment by ezequielPereyra** [comment]
@nscarcella Si, obvio. Más tarde lo hago.
